# Generated by Django 4.2.30 on 2026-05-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('insurance_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=10)),
                ('insurance_expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('inspection_status', models.CharField(choices=[('DUE', 'Due'), ('NOT_DUE', 'Not Due')], db_index=True, default='NOT_DUE', max_length=10)),
                ('inspection_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='branches.branch')),
            ],
            options={
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['branch', 'insurance_status'], name='vehicles_ve_branch__ba2eae_idx'), models.Index(fields=['insurance_status'], name='vehicles_ve_insuran_1edfb1_idx'), models.Index(fields=['inspection_status'], name='vehicles_ve_inspect_5da213_idx')],
            },
        ),
    ]
