# Generated by Django 4.2.30 on 2026-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_branch__ba2eae_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='branch',
        ),
    ]
