# Generated by Django 4.2.30 on 2026-05-15 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_remove_vehicle_vehicles_ve_branch__ba2eae_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_branch_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('practical_manual_lessons', models.PositiveIntegerField(default=0)),
                ('practical_automatic_lessons', models.PositiveIntegerField(default=0)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('number_of_trips', models.PositiveIntegerField(default=0)),
                ('student_registrations', models.PositiveIntegerField(default=0)),
                ('student_course_registrations', models.PositiveIntegerField(default=0)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('payment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exam_bookings_count', models.PositiveIntegerField(default=0)),
                ('pdl_bookings_count', models.PositiveIntegerField(default=0)),
                ('course_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'report_date'], name='reports_rep_branch__910d16_idx'), models.Index(fields=['report_date'], name='reports_rep_report__cd5337_idx'), models.Index(fields=['vehicle', 'report_date'], name='reports_rep_vehicle_04ca67_idx')],
                'unique_together': {('branch', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='PracticalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('PRACTICAL_MANUAL', 'Practical Manual'), ('PRACTICAL_AUTOMATIC', 'Practical Automatic')], db_index=True, max_length=20)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('number_of_trips', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_lessons', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_lessons_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_lessons', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='reports_pra_branch__3df874_idx'), models.Index(fields=['vehicle', 'date'], name='reports_pra_vehicle_ed81b2_idx'), models.Index(fields=['lesson_type', 'date'], name='reports_pra_lesson__0d69ae_idx')],
            },
        ),
    ]
