# Generated by Django 4.2.30 on 2026-05-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_vehicles_ve_branch__ba2eae_idx_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_entries', to='reports.report')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_entries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
