# Generated by Django 4.2.30 on 2026-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_tripentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripentry',
            name='number_of_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
