# Generated by Django 6.0.5 on 2026-08-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_lessons_to_trip_entry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practicallesson',
            name='reports_pra_branch__3df874_idx',
        ),
        migrations.RemoveIndex(
            model_name='practicallesson',
            name='reports_pra_vehicle_ed81b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='practicallesson',
            name='reports_pra_lesson__0d69ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_vehicle_04ca67_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='report',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='course_breakdown',
        ),
        migrations.RemoveField(
            model_name='report',
            name='exam_bookings_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='number_of_trips',
        ),
        migrations.RemoveField(
            model_name='report',
            name='payment_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='payment_total',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pdl_bookings_count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='practical_automatic_lessons',
        ),
        migrations.RemoveField(
            model_name='report',
            name='practical_manual_lessons',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student_course_registrations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student_registrations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='PracticalLesson',
        ),
    ]
