# Generated by Django 4.2.30 on 2026-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='desktop', max_length=10),
        ),
    ]
