# Generated by Django 4.2.30 on 2026-05-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_branch_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('GENERAL', 'General'), ('BRANCH', 'Branch')], db_index=True, default='GENERAL', max_length=10)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'), models.Index(fields=['expense_type', 'expense_date'], name='expenses_ex_expense_4677f2_idx'), models.Index(fields=['branch', 'expense_date'], name='expenses_ex_branch__593f12_idx'), models.Index(fields=['category', 'expense_date'], name='expenses_ex_categor_74f27d_idx')],
            },
        ),
    ]
