# Generated by Django 4.2.30 on 2026-06-01 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentcourse_transferred_coursetransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='registration_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
