# Generated by Django 4.2.30 on 2026-06-02 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studentcourse_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
