# Generated by Django 6.0.5 on 2026-08-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_lesson'),
        ('branches', '0002_branch_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('licence_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='academics_l_student_f0372e_idx',
            old_name='academics_lesson_student_date_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='academics_l_student_af3f16_idx',
            old_name='academics_lesson_sc_status_idx',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('onboarded', 'Onboarded'), ('pending_pdl', 'Pending PDL'), ('active', 'Active'), ('pending_exam_booking', 'Pending Exam'), ('exam_booked', 'Exam List'), ('exam_approved', 'Exam Approved'), ('failed', 'Failed'), ('retake_booked', 'Retake Booked'), ('completed', 'Completed'), ('dormant', 'Dormant'), ('transferred', 'Transferred')], db_index=True, default='onboarded', max_length=30),
        ),
        migrations.AddField(
            model_name='instructor',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='academics.instructor'),
        ),
    ]
