# Generated by Django 6.0.5 on 2026-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_lessons_integer_exam_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('practical', 'Practical'), ('theory', 'Theory')], default='practical', max_length=50),
        ),
    ]
