# Generated by Django 6.0.5 on 2026-08-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_pdlbooking_pdl_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambooking',
            name='admin1_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exambooking',
            name='admin2_comment',
            field=models.TextField(blank=True),
        ),
    ]
