# Generated by Django 6.0.5 on 2026-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_exam_booking_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlbooking',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdlbooking',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
