# Generated by Django 6.0.4 on 2026-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='reference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
