# Generated by Django 6.0.4 on 2026-05-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentconfirmation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
