# Generated by Django 6.0.4 on 2026-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymenttransaction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('orphaned', 'Orphaned')], default='completed', max_length=20),
        ),
    ]
