# Generated by Django 4.2.30 on 2026-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['student', 'status'], name='finance_pay_student_580767_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='finance_pay_status_576a82_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['student_course', 'status'], name='finance_pay_student_1ee5b7_idx'),
        ),
    ]
