# Generated by Django 6.0.5 on 2026-05-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_paymenttransaction_payment_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='finance_payment_type_idx',
        ),
    ]
