# Generated by Django 6.0.5 on 2026-05-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payment_type_retake_pdl_reactivation'),
        ('finance', '0010_remove_paymenttransaction_finance_payment_type_idx'),
    ]

    operations = [
    ]
