# Generated by Django 6.0.5 on 2026-05-26 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_merge_20260526_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cleared_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('cust_memo_line1', models.CharField(blank=True, max_length=255)),
                ('cust_memo_line2', models.CharField(blank=True, max_length=255)),
                ('cust_memo_line3', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('exchange_rate', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(blank=True, max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('transaction_reference_code', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('institution_code', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymentconfirmation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='paymentconfirmation',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='data',
        ),
        migrations.RemoveField(
            model_name='paymentconfirmation',
            name='reference',
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='connection_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='document_reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='institution_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_reference_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='finance.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='raw_payload',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfirmation',
            name='transaction_reference_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['account_number'], name='finance_pay_account_c13c78_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['transaction_reference_code'], name='finance_pay_transac_c73144_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['payment_reference_code'], name='finance_pay_payment_dcefec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentconfirmation',
            index=models.Index(fields=['created_at'], name='finance_pay_created_f1c4a4_idx'),
        ),
        migrations.AddField(
            model_name='banknotification',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_notifications', to='finance.paymenttransaction'),
        ),
        migrations.AddIndex(
            model_name='paymentvalidation',
            index=models.Index(fields=['transaction_reference_code'], name='finance_pay_transac_bd5a91_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvalidation',
            index=models.Index(fields=['created_at'], name='finance_pay_created_3a8255_idx'),
        ),
        migrations.AddIndex(
            model_name='banknotification',
            index=models.Index(fields=['account_number'], name='finance_ban_account_5409d2_idx'),
        ),
        migrations.AddIndex(
            model_name='banknotification',
            index=models.Index(fields=['transaction_id'], name='finance_ban_transac_54ff2c_idx'),
        ),
        migrations.AddIndex(
            model_name='banknotification',
            index=models.Index(fields=['payment_ref'], name='finance_ban_payment_2bd0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='banknotification',
            index=models.Index(fields=['event_type', 'created_at'], name='finance_ban_event_t_c01511_idx'),
        ),
    ]
