# Generated by Django 4.2.30 on 2026-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_banknotification_paymentvalidation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('TOP_UP', 'Top-Up'), ('RETAKE', 'Retake'), ('PDL_REACTIVATION', 'PDL Reactivation'), ('UNALLOCATED', 'Unallocated')], default='TOP_UP', max_length=20),
        ),
    ]
