# Generated by Django 4.2.30 on 2026-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_unallocated_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank'), ('coop_stk', 'Co-op STK'), ('bank_ipn', 'Bank Transfer (IPN)'), ('bank_b2b', 'Bank (B2B)')], default='bank', max_length=20),
        ),
    ]
