# Generated by Django 4.2.30 on 2026-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_payment_method_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='mpesa_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
