# Generated by Django 4.2.30 on 2026-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_mpesa_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('TOP_UP', 'Top-Up'), ('RETAKE', 'Retake'), ('PDL_REACTIVATION', 'PDL Reactivation'), ('UNALLOCATED', 'Unallocated'), ('CREDIT_TRANSFER', 'Credit Transfer')], default='TOP_UP', max_length=20),
        ),
    ]
