# Generated by Django 4.2.30 on 2026-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_paymenttransaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
