# Generated by Django 4.2.30 on 2026-06-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_phone_number'),
        ('finance', '0018_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphaned_payments', to='branches.branch'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['branch', 'status'], name='finance_pay_branch__707086_idx'),
        ),
    ]
